# -*- coding: utf-8 -*-
"""desafio15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRC5Y9ngmhqsMt_DUm7JziTQCJMgDvq-
"""

using Distributed
addprocs(4) # Adiciona 4 processos (workers) para paralelismo. O número pode ser ajustado.

@everywhere function expensive_computation(n)
    # Aumentar a complexidade da computação
    result = 0.0
    for _ in 1:n
        # Exemplo de operação mais intensiva: multiplicação de matrizes pequenas
        # Isso é uma simplificação, mas aumenta o trabalho por iteração.
        matrix_a = rand(2, 2)
        matrix_b = rand(2, 2)
        matrix_c = matrix_a * matrix_b
        result += sum(matrix_c)
    end
    return result
end

println("Workers adicionados: ", nworkers())

"""Com os workers adicionados, agora podemos comparar a execução em série e em paralelo."""

# Configurações para os testes
num_iterations = 100000000 # Reduzindo o número de iterações para cada tarefa, mas a tarefa em si é mais pesada
num_tasks = 8 # Número de tarefas a serem distribuídas

println("\n--- Execução em Série ---")
time_serial = @elapsed begin
    results_serial = []
    for _ in 1:num_tasks
        push!(results_serial, expensive_computation(num_iterations))
    end
end
println("Tempo gasto (série): ", time_serial, " segundos")

println("\n--- Execução em Paralelo ---")
time_parallel = @elapsed begin
    results_parallel = @distributed (vcat) for _ in 1:num_tasks
        expensive_computation(num_iterations)
    end
end
println("Tempo gasto (paralelo): ", time_parallel, " segundos")

println("\nComparação:")
println("O loop paralelo foi ", round(time_serial / time_parallel, digits=2), " vezes mais rápido que o loop em série.")

"""Este exemplo demonstra como os loops paralelos podem reduzir significativamente o tempo de execução para tarefas computacionalmente intensivas, distribuindo o trabalho entre múltiplos 'workers' ou threads. Os resultados exatos podem variar dependendo do número de núcleos de CPU disponíveis e da natureza da computação."""